import Head from 'next/head'
import HomepageVariantA from '@/components/VariantA/HomePage/HomepageVariantA'
import DataLibraryVariantA from '@/components/VariantA/DataLibrary/DataLibraryVariantA'
import { NextSeo } from 'next-seo'

export default function DataLiberary() {
  return (
    <>
      <Head>
        <title>Data Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NextSeo
        title="Data Library"
        description="Data Library"
        canonical="https://www.canonical.ie/"
        openGraph={{
          url: 'https://www.url.ie/a',
          title: 'Data Library',
          description: 'Data Library',
          images: [
            {
              url: 'https://www.example.ie/og-image-01.jpg',
              width: 800,
              height: 600,
              alt: 'Og Image Alt',
              type: 'image/jpeg',
            },
          ],
          siteName: 'SiteName',
        }}
        twitter={{
          handle: '@handle',
          site: '@site',
          cardType: 'summary_large_image',
        }}
      />
      <main>
      <DataLibraryVariantA />
      </main>
    </>
  )
}
